module FSBar.Client.Tests.ChokepointsTests

open System
open System.IO
open Xunit
open FSBar.Client
open FSBar.SyntheticData

// Base centre placed firmly on one side of the wall generated by oneGapCorridor.
// The helper places the wall at heightmap-corner column x ≈ width/2, so a base
// in the left half is unambiguously separated from the right half.
let baseCentreForOneGap (width: int) (height: int) : float32 * float32 * float32 =
    float32 (width / 4) * 8.0f, 0.0f, float32 (height / 2) * 8.0f

// ---------------------------------------------------------------------------
// Layer-1 unit tests
// ---------------------------------------------------------------------------

[<Fact>]
let ``findChokepoints on fully open grid returns empty`` () =
    let grid = SyntheticMapGrid.flat 32 32
    let q = Chokepoints.defaultChokepointQuery MoveType.Kbot
    let cps = Chokepoints.findChokepoints grid (128.0f, 0.0f, 128.0f) q
    Assert.Equal<Chokepoint list>([], cps)

[<Fact>]
let ``findChokepoints on one-gap corridor returns a single chokepoint`` () =
    // 64x64 grid, 3-corner gap.
    let grid = SyntheticMapGrid.oneGapCorridor 64 64 3
    let baseCentre = baseCentreForOneGap 64 64
    let q =
        { Chokepoints.defaultChokepointQuery MoveType.Kbot with
            MaxWidthElmos = 80.0f
            SearchRadiusElmos = 4096.0f }
    let cps = Chokepoints.findChokepoints grid baseCentre q
    Assert.True(cps.Length >= 1, sprintf "expected at least one chokepoint, got %d" cps.Length)
    // The top-ranked chokepoint should sit near the wall column (~ world x = 256).
    let top = cps.[0]
    let (tx, _, _) = top.Position
    Assert.InRange(tx, 200.0f, 320.0f)
    Assert.True(top.WidthElmos > 0.0f)

[<Fact>]
let ``findChokepoints is deterministic across identical invocations`` () =
    let grid = SyntheticMapGrid.oneGapCorridor 64 64 3
    let baseCentre = baseCentreForOneGap 64 64
    let q =
        { Chokepoints.defaultChokepointQuery MoveType.Kbot with
            MaxWidthElmos = 80.0f
            SearchRadiusElmos = 4096.0f }
    let a = Chokepoints.findChokepoints grid baseCentre q
    let b = Chokepoints.findChokepoints grid baseCentre q
    Assert.Equal(a.Length, b.Length)
    for i in 0 .. a.Length - 1 do
        Assert.Equal(a.[i].Id, b.[i].Id)
        Assert.Equal(a.[i].Position, b.[i].Position)
        Assert.Equal(a.[i].WidthElmos, b.[i].WidthElmos)

[<Fact>]
let ``chokepointIdOf is stable for the same ridge cell across calls`` () =
    let grid = SyntheticMapGrid.flat 32 32
    let a = Chokepoints.chokepointIdOf grid 10 15
    let b = Chokepoints.chokepointIdOf grid 10 15
    Assert.Equal(a, b)
    let c = Chokepoints.chokepointIdOf grid 10 16
    Assert.NotEqual(a, c)

[<Fact>]
let ``computeDistanceTransform returns the same shape as passability`` () =
    let grid = SyntheticMapGrid.flat 32 32
    let dt = Chokepoints.computeDistanceTransform grid MoveType.Kbot Seq.empty
    let pass = MapGrid.passability grid MoveType.Kbot
    Assert.Equal(Array2D.length1 pass, Array2D.length1 dt)
    Assert.Equal(Array2D.length2 pass, Array2D.length2 dt)
    // Interior cells should have dt roughly equal to distance from the map edge.
    // (The map edge acts as a virtual impassable border.)
    let w = Array2D.length1 dt
    let h = Array2D.length2 dt
    // Pick a few sample cells and check dt > 0.
    Assert.True(dt.[w / 2, h / 2] > 0.0f)
    Assert.True(dt.[0, 0] >= 0.0f)

// ---------------------------------------------------------------------------
// Layer-2 integration test (skipped without Avalanche)
// ---------------------------------------------------------------------------

let avalanchePath =
    let home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)
    Path.Combine(home, ".local", "state", "Beyond All Reason", "maps", "avalanche_3.4.sd7")

[<Fact>]
let ``Layer-2 findChokepoints on Avalanche returns non-empty list and is deterministic`` () =
    // The union-find bridge algorithm runs in O(N log N) (~250ms on Avalanche's
    // 513 × 513 heightmap), so we use realistic macro-bot query parameters here:
    // MaxWidth=240 covers canyon entrances up to 240 elmos wide, SearchRadius=5500
    // covers the whole map diagonal from the Player-1 start corner.
    if not (File.Exists avalanchePath) then () else
    match SmfParser.parseSd7 avalanchePath with
    | Result.Error e -> Assert.Fail(sprintf "SMF parse failed: %A" e)
    | Result.Ok smf ->
        let grid = SmfParser.toMapGrid smf
        let q =
            { Chokepoints.defaultChokepointQuery MoveType.Kbot with
                MaxWidthElmos = 240.0f
                SearchRadiusElmos = 5500.0f }
        let baseCentre = (500.0f, 0.0f, 397.0f)
        let sw = System.Diagnostics.Stopwatch.StartNew()
        let cps = Chokepoints.findChokepoints grid baseCentre q
        sw.Stop()
        Assert.True(sw.ElapsedMilliseconds < 5_000L,
            sprintf "findChokepoints took %dms; expected < 5000" sw.ElapsedMilliseconds)
        Assert.True(cps.Length >= 1,
            sprintf "expected ≥1 chokepoint on Avalanche, got 0")
        // Every returned chokepoint must have a positive width and positive distance.
        for cp in cps do
            Assert.True(cp.WidthElmos > 0.0f)
            Assert.True(cp.DistanceFromBase > 0.0f)
        // Determinism: two calls return identical id lists.
        let cps2 = Chokepoints.findChokepoints grid baseCentre q
        Assert.Equal(cps.Length, cps2.Length)
        for i in 0 .. cps.Length - 1 do
            Assert.Equal(cps.[i].Id, cps2.[i].Id)
            Assert.Equal(cps.[i].Position, cps2.[i].Position)
